### ISSUE TITLE
XML deserialization error regarding BuildCompletionEvent

### ISSUE THREAD

**Issue by dambrisco** [timclipsham/tfs-hipchat#7]
It appears that the BuildCompletionObject does not match the format of the XML object sent by the latest version of TFS 2012 (update 3). It seems odd that they'd change the format without a major version release, so if this can't be confirmed by a second party I'll dig into what's really happening.

**Comment by timclipsham** [comment]
Interesting...

We haven't updated our TFS 2012 instance to Update 3 yet, but I'll see if I
can do it today and check if we have the same issue.

FYI: You can wire up a notification in TFS to be sent to http://respondto.it.
It's a really useful service for observing the XML being sent in the HTTP
request with minimal effort.

**Comment by timclipsham** [comment]
I think our installation was still RTM actually. Nevertheless we've upgraded to Update 3.

My existing notifications continued to work without issue, but I think I've discovered the problem.

There's several event types in TFS for build notifications. The ones I created were through the command line and specifically for `BuildComple_tion_Event`. There's also a `BuildComple_tion_Event2` and a `BuildComplet_ed_Event`.  It seems the web UI for TFS 2012 uses the `BuildCompletedEvent` type.

TFS HipChat only supports `BuildCompletionEvent` currently, and I'm about half way through a fix to also support `BuildCompletedEvent`. In the meantime, you can add the `BuildCompletionEvent` using the command line (`BisSubscribe.exe`) instead for build notifications.

Hope that helps! Thanks again for raising the issue.

**Comment by timclipsham** [comment]
TFS HipChat now supports `BuildCompletedEvent` and `BuildCompletionEvent2`.

Handling build events through the TFS 2012 web UI should work properly now. Give it a go :)
